CONFIG_DEBUG=y
CONFIG_WOLFSSL=y

EXPORTED_FUNCTIONS='[ "_wcjs_alloc", "_wcjs_free", "_randomBytesAlloc", "_generateInitializationVector",  "_decryptWithPrivateKey", "_encryptWithPublicKey", "_hmac", "_init", "_deinit", "_generateKey", "_generateKeyPair", "_sha256", "_encryptor", "_decryptor" ]'


ROOT_DIR        :=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
PREFIX          := $(ROOT_DIR)/local


ifdef CONFIG_DEBUG
    OFLAGS := -g3 -O0
else
    OFLAGS = -O3
endif

MDS             := $(wildcard *.txt)
OBJS            := $(CMD).o
WOLFSSL         := $(ROOT_DIR)/../..
INCLUDES_LIB    := -I$(PREFIX)/include
INCLUDES        := -I$(WOLFSSL) -I$(ROOT_DIR)

EMCONFIGURE     := $(shell which emconfigure)

ifdef CONFIG_WOLFSSL
    CFLAGS += -DCONFIG_WOLFSSL -Wno-implicit-function-declaration
    CFLAGS_USER = -DWOLFSSL_USER_SETTINGS
endif

ifdef CONFIG_DEBUG
    CFLAGS += -DCONFIG_DEBUG -DDEBUG_WOLFSSL
endif

CFLAGS += $(OFLAGS)

CFLAGS_LIB = $(CFLAGS)
CFLAGS += $(CFLAGS_USER)
